"""
This type stub file was generated by pyright.
"""

import PySide6.QtCore
import PySide6.Qt3DCore
import typing
from PySide6.QtCore import Signal
from shiboken6 import Shiboken

"""
This file contains the exact signatures for all functions in module
PySide6.Qt3DLogic, except for defaults which are replaced by "...".
"""
class QIntList:
    ...


class Qt3DLogic(Shiboken.Object):
    class QFrameAction(PySide6.Qt3DCore.Qt3DCore.QComponent):
        triggered: typing.ClassVar[Signal] = ...
        def __init__(self, /, parent: PySide6.Qt3DCore.Qt3DCore.QNode | None = ...) -> None:
            ...
        
    
    
    class QLogicAspect(PySide6.Qt3DCore.Qt3DCore.QAbstractAspect):
        def __init__(self, /, parent: PySide6.QtCore.QObject | None = ...) -> None:
            ...
        
    
    


