"""
This type stub file was generated by pyright.
"""

import PySide6.QtConcurrent
import PySide6.QtCore
import enum
import typing
from shiboken6 import Shiboken

"""
This file contains the exact signatures for all functions in module
PySide6.QtConcurrent, except for defaults which are replaced by "...".
"""
class QFutureQString(Shiboken.Object):
    @typing.overload
    def __init__(self, /) -> None:
        ...
    
    @typing.overload
    def __init__(self, QFutureQString: PySide6.QtConcurrent.QFutureQString, /) -> None:
        ...
    
    def __copy__(self, /) -> typing.Self:
        ...
    
    def cancel(self, /) -> None:
        ...
    
    def cancelChain(self, /) -> None:
        ...
    
    def isCanceled(self, /) -> bool:
        ...
    
    def isFinished(self, /) -> bool:
        ...
    
    def isPaused(self, /) -> bool:
        ...
    
    def isRunning(self, /) -> bool:
        ...
    
    def isStarted(self, /) -> bool:
        ...
    
    def isSuspended(self, /) -> bool:
        ...
    
    def isSuspending(self, /) -> bool:
        ...
    
    def isValid(self, /) -> bool:
        ...
    
    def pause(self, /) -> None:
        ...
    
    def progressMaximum(self, /) -> int:
        ...
    
    def progressMinimum(self, /) -> int:
        ...
    
    def progressText(self, /) -> str:
        ...
    
    def progressValue(self, /) -> int:
        ...
    
    def resultCount(self, /) -> int:
        ...
    
    def resume(self, /) -> None:
        ...
    
    def setPaused(self, paused: bool, /) -> None:
        ...
    
    def setSuspended(self, suspend: bool, /) -> None:
        ...
    
    def suspend(self, /) -> None:
        ...
    
    def togglePaused(self, /) -> None:
        ...
    
    def toggleSuspended(self, /) -> None:
        ...
    
    def waitForFinished(self, /) -> None:
        ...
    


class QFutureVoid(Shiboken.Object):
    @typing.overload
    def __init__(self, /) -> None:
        ...
    
    @typing.overload
    def __init__(self, QFutureVoid: PySide6.QtConcurrent.QFutureVoid, /) -> None:
        ...
    
    def __copy__(self, /) -> typing.Self:
        ...
    
    def cancel(self, /) -> None:
        ...
    
    def cancelChain(self, /) -> None:
        ...
    
    def isCanceled(self, /) -> bool:
        ...
    
    def isFinished(self, /) -> bool:
        ...
    
    def isPaused(self, /) -> bool:
        ...
    
    def isRunning(self, /) -> bool:
        ...
    
    def isStarted(self, /) -> bool:
        ...
    
    def isSuspended(self, /) -> bool:
        ...
    
    def isSuspending(self, /) -> bool:
        ...
    
    def isValid(self, /) -> bool:
        ...
    
    def pause(self, /) -> None:
        ...
    
    def progressMaximum(self, /) -> int:
        ...
    
    def progressMinimum(self, /) -> int:
        ...
    
    def progressText(self, /) -> str:
        ...
    
    def progressValue(self, /) -> int:
        ...
    
    def resultCount(self, /) -> int:
        ...
    
    def resume(self, /) -> None:
        ...
    
    def setPaused(self, paused: bool, /) -> None:
        ...
    
    def setSuspended(self, suspend: bool, /) -> None:
        ...
    
    def suspend(self, /) -> None:
        ...
    
    def togglePaused(self, /) -> None:
        ...
    
    def toggleSuspended(self, /) -> None:
        ...
    
    def waitForFinished(self, /) -> None:
        ...
    


class QFutureWatcherQString(PySide6.QtCore.QObject):
    def __init__(self, /, _parent: PySide6.QtCore.QObject | None = ...) -> None:
        ...
    
    def future(self, /) -> PySide6.QtConcurrent.QFutureQString:
        ...
    
    def setFuture(self, future: PySide6.QtConcurrent.QFutureQString, /) -> None:
        ...
    


class QFutureWatcherVoid(PySide6.QtCore.QObject):
    def __init__(self, /, _parent: PySide6.QtCore.QObject | None = ...) -> None:
        ...
    


class QIntList:
    ...


class QtConcurrent(Shiboken.Object):
    class FutureResult(enum.Enum):
        Ignore = ...
    
    
    class ReduceOption(enum.Flag):
        UnorderedReduce = ...
        OrderedReduce = ...
        SequentialReduce = ...
    
    
    class ThreadFunctionResult(enum.Enum):
        ThrottleThread = ...
        ThreadFinished = ...
    
    


