"""
This type stub file was generated by pyright.
"""

from shiboken6 import Shiboken

"""
This file contains the exact signatures for all functions in module
PySide6.QtWebView, except for defaults which are replaced by "...".
"""
class QIntList:
    ...


class QtWebView(Shiboken.Object):
    @staticmethod
    def initialize() -> None:
        ...
    


