"""
This type stub file was generated by pyright.
"""

import collections.abc

"""
This file contains the exact signatures for all functions in module
PySide6.QtQuickTest, except for defaults which are replaced by "...".
"""
class QIntList:
    ...


def QUICK_TEST_MAIN(name: str, /, argv: collections.abc.Sequence[str] = ..., dir: str = ...) -> int:
    ...

def QUICK_TEST_MAIN_WITH_SETUP(name: str, setup: type, /, argv: collections.abc.Sequence[str] = ..., dir: str = ...) -> int:
    ...

