"""
This type stub file was generated by pyright.
"""

import collections.abc
import contextvars
from . import events, futures
from typing import Any

class QAsyncioTask(futures.QAsyncioFuture):
    """ https://docs.python.org/3/library/asyncio-task.html """
    def __init__(self, coro: collections.abc.Generator | collections.abc.Coroutine, *, loop: events.QAsyncioEventLoop | None = ..., name: str | None = ..., context: contextvars.Context | None = ...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    class QtTaskApiMisuseError(Exception):
        ...
    
    
    def set_result(self, result: Any) -> None:
        ...
    
    def set_exception(self, exception: Any) -> None:
        ...
    
    def get_stack(self, *, limit=...) -> list[Any]:
        ...
    
    def print_stack(self, *, limit=..., file=...) -> None:
        ...
    
    def get_coro(self) -> collections.abc.Generator | collections.abc.Coroutine:
        ...
    
    def get_name(self) -> str:
        ...
    
    def set_name(self, value) -> None:
        ...
    
    def cancel(self, msg: str | None = ...) -> bool:
        ...
    
    def uncancel(self) -> int:
        ...
    
    def cancelling(self) -> int:
        ...
    


